# Netlify configuration for Coffee Precision PWA

[build]
  # No build process needed - static files
  publish = "."
  
[build.environment]
  NODE_VERSION = "18"

# Headers for PWA support
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Service Worker caching
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
    Service-Worker-Allowed = "/"

# Manifest.json headers
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=31536000"

# Icon caching
[[headers]]
  for = "/icon-*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# CSS and JS caching
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# HTML no-cache for updates
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "no-cache"

# Redirects (optional)
[[redirects]]
  from = "/app"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/calculate"
  to = "/index.html"
  status = 200

# Force HTTPS
[[redirects]]
  from = "http://coffee-precision-app.netlify.app/*"
  to = "https://coffee-precision-app.netlify.app/:splat"
  status = 301
  force = true

# 404 fallback to main app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200